### ISSUE TITLE
Services cannot be deployed to GKE clusters

### ISSUE THREAD

**Issue by jbw976** [upbound/platform-ref-multi-k8s#5]
Because Basic Auth is not enabled by default, the kubeconfig that provider-helm is given in the services composition is not sufficient to connect and deploy the services helm chart.

I think we need to update the GKE composition to include something like this:
```
masterAuth:
  username: multik8sadmin
masterAuthorizedNetworksConfig:
  enabled: false
```

Note that this will not be a long term solution, because basic auth was removed completely in 1.19+.  We'll need to support oauth as described in https://github.com/crossplane-contrib/provider-helm/issues/72.
